### ISSUE TITLE
Change required SEO properties

### ISSUE THREAD

**Issue by dmyers** [Calotype/SEO#3]
https://support.google.com/webmasters/answer/71453?hl=en

Google claims to only require the `loc` property and that `lastmod` is optional and they don't list any others.

http://www.google.com/sitemap.xml

**Comment by bryantebeek** [comment]
Please take a look at the official sitemap protocol at http://www.sitemaps.org/protocol.html

Indeed they only require `loc`, but the page you are referring to is not an actual sitemap, but a sitemap index file.

**Comment by bryantebeek** [comment]
Only loc is required \*
