### ISSUE TITLE
Move routes to controllers?

### ISSUE THREAD

**Issue by dmyers** [Calotype/SEO#4]
What do you think of moving Sitemap and Robots routes to controllers? I wanted to be able to write my own sitemap controller to populate the sitemap before rendering, but I wasn't sure where to do so I made a new route and controller, but I think it would be nicer to just not have to add a route overriding the package.

**Comment by bryantebeek** [comment]
I made the generated routes optional using a configuration.

I hope this solves your issues, if not, just hit me ;)
