### ISSUE TITLE
Canonical link tag support

### ISSUE THREAD

**Issue by dmyers** [Calotype/SEO#6]
What do you think of adding support for canonical link tags? I'm using this package and would really like it as it looks like I need it.

Here's an article on Google Webmasters page:
https://support.google.com/webmasters/answer/139066?hl=en

If you do I could send a PR or if you have a preferred method of implementation. I'd appreciate it either way.

**Comment by dmyers** [comment]
@Calotype Any thoughts? Also I noticed some rebranding commits? You should be able to rebase them out and then do a force git push to get rid of them out of the history. I do it a lot when I am testing new stuff on a branch.

**Comment by bryantebeek** [comment]
@dmyers I should do that indeed, it had to do with me switching jobs and my current employer didn't want to use a package that was not fully under his control.

Could you give a short example on how you'd like to use it? 

PR's are welcome anytime :)

**Comment by dmyers** [comment]
@bryantebeek Ah makes sense, been there.

Good question. I was thinking something like `Meta::setCanonical('http://')` maybe? I know it's not really a meta tag though just not sure as it's a link tag, but could be under the `meta` system which stores it.

**Comment by bryantebeek** [comment]
Yea, I was wondering whether or not it should go under `meta`or not, but it seems reasonable to do so. I'll take a look at the implementation. :)

**Comment by bryantebeek** [comment]
@dmyers Any change you've got Skype or something so we can chat a bit :)

**Comment by dmyers** [comment]
@bryantebeek Oops I forgot to respond. I just saw you had added it and it works great! Thanks for adding it! My Skype handle is arcticpro.
