### ISSUE TITLE
Custom meta name support

### ISSUE THREAD

**Issue by dmyers** [Calotype/SEO#7]
I was looking to implement [Twitter cards](https://dev.twitter.com/docs/cards) so I was thinking either a new type like Facebook's OpenGraph or be able to create new meta name/value pairs. What do you think @bryantebeek?

**Comment by bryantebeek** [comment]
@dmyers I'd go with a new generator, just like the OpenGraphGenerator. Something like a TwitterCardGenerator.

**Comment by dmyers** [comment]
Moved to #8
